#include "ui/motivational_lines.hpp"

#include "common/i18n.hpp"

#include <algorithm>
#include <cstddef>
#include <deque>
#include <iterator>
#include <random>

namespace mosaic::ui {
namespace {

// The one-liners behind Settings → Annoyances → "Cheesy motivational one-liners": mostly earnest
// encouragement with a generous sprinkle of absurd / Mosaic-aware meta humour. ALL-CAPS is
// deliberate -- the deadpan delivery is the joke. Each is wrapped in the extraction marker (call it
// the macro by its three letters, M-O-T-I-V-A-T-E-underscore, spelled out here so this comment does
// not itself look like an entry) so the pot-motivate target extracts them into po/motivate.pot without
// touching po/mosaic.pot.
//
// The table is SIZE-DEDUCED on purpose (a plain array + std::size, not std::array<…, N>): a fixed
// count would silently value-initialize any shortfall to nullptr, and one missing entry once shipped
// exactly that -- a null line ~1/N of the time, straight into std::string. With a deduced size that
// class of bug cannot recur.
constexpr const char* kLines[] = {
    // -- earnest: encouragement, self-care, craft ----------------------------------------------
    MOTIVATE_("I BELIEVE IN YOU"),
    MOTIVATE_("YOU CAN DO IT"),
    MOTIVATE_("YOUR ART MATTERS"),
    MOTIVATE_("KEEP GOING"),
    MOTIVATE_("ONE STROKE AT A TIME"),
    MOTIVATE_("YOU ARE DOING BETTER THAN YOU THINK"),
    MOTIVATE_("PROGRESS, NOT PERFECTION"),
    MOTIVATE_("EVERY MASTERPIECE STARTED AS A BLANK CANVAS"),
    MOTIVATE_("TRUST THE PROCESS"),
    MOTIVATE_("YOUR LINEWORK IS IMPROVING"),
    MOTIVATE_("TAKE A SIP OF WATER, CHAMPION"),
    MOTIVATE_("STRETCH THOSE WRISTS"),
    MOTIVATE_("BREATHE, THEN PAINT"),
    MOTIVATE_("MISTAKES ARE JUST HAPPY DETOURS"),
    MOTIVATE_("UNDO IS ALWAYS THERE FOR YOU"),
    MOTIVATE_("NOBODY DRAWS HANDS RIGHT THE FIRST TIME"),
    MOTIVATE_("YOU SHOWED UP TODAY, AND THAT COUNTS"),
    MOTIVATE_("THAT COLOR CHOICE IS BOLD AND I LOVE IT"),
    MOTIVATE_("KEEP THAT LAYER, IT IS GOOD"),
    MOTIVATE_("SAVE YOUR WORK, THEN KEEP GOING"),
    MOTIVATE_("YOUR STYLE IS YOURS ALONE"),
    MOTIVATE_("CREATIVITY LOOKS GOOD ON YOU"),
    MOTIVATE_("THE BLANK CANVAS FEARS YOU"),
    MOTIVATE_("YOU HAVE GOT THIS"),
    MOTIVATE_("ALMOST THERE"),
    MOTIVATE_("PROUD OF YOU"),
    MOTIVATE_("ART IS NEVER WASTED TIME"),
    MOTIVATE_("YOU ARE ENOUGH"),
    MOTIVATE_("FINISH THE SKETCH, FUTURE YOU WILL THANK YOU"),
    MOTIVATE_("SMALL STEPS STILL MOVE FORWARD"),
    MOTIVATE_("YOUR HANDS MAKE WONDERFUL THINGS"),
    MOTIVATE_("DOUBT LESS, DRAW MORE"),
    MOTIVATE_("THE WORLD NEEDS YOUR WEIRD IDEAS"),
    MOTIVATE_("GOOD ENOUGH IS STILL GOOD"),
    MOTIVATE_("KEEP THAT SPARK ALIVE"),
    MOTIVATE_("YOU ARE NOT STUCK, YOU ARE MARINATING"),
    MOTIVATE_("REST IS PART OF THE WORK"),
    MOTIVATE_("THAT IS LOOKING REALLY NICE"),
    MOTIVATE_("ONE MORE LAYER, ONE MORE WIN"),
    MOTIVATE_("YOU CAME THIS FAR ALREADY"),
    MOTIVATE_("CREATE FOR THE JOY OF IT"),
    MOTIVATE_("NO ONE ELSE SEES IT QUITE LIKE YOU"),
    MOTIVATE_("BE PATIENT WITH YOURSELF"),
    MOTIVATE_("THE GOOD PART IS COMING"),
    MOTIVATE_("KEEP YOUR CHIN UP AND YOUR STYLUS DOWN"),
    MOTIVATE_("EVERY EXPERT WAS ONCE A BEGINNER"),
    MOTIVATE_("DRAW IT BADLY FIRST, THEN FIX IT"),
    MOTIVATE_("YOU ARE ALLOWED TO MAKE BAD ART"),
    MOTIVATE_("TOMORROW YOU IS ALREADY CHEERING"),
    MOTIVATE_("THE HARD PART MEANS YOU ARE LEARNING"),
    MOTIVATE_("ZOOM OUT AND SEE HOW FAR YOU HAVE COME"),
    MOTIVATE_("ART DOES NOT HAVE TO BE PERFECT TO BE LOVED"),
    MOTIVATE_("YOU AND THIS CANVAS ARE UNSTOPPABLE"),
    MOTIVATE_("THE FIRST DRAFT IS SUPPOSED TO BE ROUGH"),
    MOTIVATE_("YOU ARE ALLOWED TO LIKE YOUR OWN WORK"),
    MOTIVATE_("MAKE THE THING, THEN MAKE IT BETTER"),
    MOTIVATE_("CREATIVITY IS A MUSCLE AND YOURS IS FLEXING"),
    MOTIVATE_("SLOW DOWN, IT IS NOT A RACE"),
    MOTIVATE_("THE BLANK PARTS ARE FULL OF POSSIBILITY"),
    MOTIVATE_("YOU HAVE SURVIVED EVERY ART BLOCK SO FAR"),
    MOTIVATE_("SAVE OFTEN, DREAM BIG"),
    MOTIVATE_("THAT WAS A GOOD STROKE, DO ANOTHER"),
    MOTIVATE_("YOU ARE THE ARTIST THIS CANVAS NEEDED"),
    MOTIVATE_("BE KIND TO YOURSELF TODAY"),
    MOTIVATE_("DONE IS BETTER THAN PERFECT"),
    MOTIVATE_("YOU MAKE HARD THINGS LOOK EASY"),
    MOTIVATE_("KEEP THE PARTS YOU LIKE"),
    MOTIVATE_("YOU ARE EXACTLY WHERE YOU NEED TO BE"),
    MOTIVATE_("BLINK, YOUR EYES HAVE BEEN STARING"),
    MOTIVATE_("UNCLENCH YOUR JAW, ARTIST"),
    MOTIVATE_("ROLL YOUR SHOULDERS BACK"),
    MOTIVATE_("YOU ARE BUILDING SOMETHING ONLY YOU COULD"),
    MOTIVATE_("THE SKETCH UNDERNEATH IS ALLOWED TO BE MESSY"),
    MOTIVATE_("YOUR TASTE IS AHEAD OF YOUR SKILL, AND THAT IS GROWTH"),
    MOTIVATE_("START UGLY, FINISH PROUD"),
    MOTIVATE_("ONE GOOD CURVE AT A TIME"),
    MOTIVATE_("LET IT BE A LITTLE WONKY"),
    MOTIVATE_("YOUR FUTURE PORTFOLIO IS CHEERING"),
    MOTIVATE_("PUT IT ON A LAYER AND DECIDE LATER"),
    MOTIVATE_("STEP BACK AND SQUINT, IT HELPS"),
    MOTIVATE_("YOU DO NOT HAVE TO FINISH IT TONIGHT"),
    MOTIVATE_("THE WORK REMEMBERS EVERY HOUR YOU GAVE IT"),
    MOTIVATE_("KEEP DRAWING THE THING YOU CANNOT STOP THINKING ABOUT"),
    MOTIVATE_("NOBODY IS BORN KNOWING PERSPECTIVE"),
    MOTIVATE_("YOU ARE CLOSER THAN YOU WERE AN HOUR AGO"),
    MOTIVATE_("EVEN A ROUGH DAY MAKES A REAL MARK"),
    MOTIVATE_("YOUR HANDS KNOW MORE THAN YOU THINK"),
    MOTIVATE_("GIVE THE IDEA ROOM TO BE BAD FIRST"),
    MOTIVATE_("THE ONLY BAD DRAWING IS THE ONE YOU DID NOT START"),
    MOTIVATE_("KEEP THE FIRST LINE, IT WAS HONEST"),
    MOTIVATE_("YOUR WEIRDEST IDEA IS PROBABLY YOUR BEST ONE"),
    MOTIVATE_("LOOK HOW FAR THIS PIECE HAS COME"),
    MOTIVATE_("YOU ARE NOT BEHIND, YOU ARE ON YOUR OWN CLOCK"),
    MOTIVATE_("MORE PEOPLE WILL LOVE THIS THAN YOU EXPECT"),
    MOTIVATE_("THE FUN PART IS WORTH THE BORING PART"),
    MOTIVATE_("YOU GET TO MAKE THINGS, HOW LUCKY IS THAT"),
    MOTIVATE_("A LITTLE EVERY DAY BEATS A LOT NEVER"),
    MOTIVATE_("LET THE FIRST PASS BE TERRIBLE"),
    MOTIVATE_("YOUR INSTINCTS ARE WORTH TRUSTING"),
    // -- absurd / Mosaic-aware / meta ----------------------------------------------------------
    MOTIVATE_("HORSING AROUND?"),
    MOTIVATE_("THE PIXELS RESPECT YOU"),
    MOTIVATE_("CTRL+S IS A LOVE LANGUAGE"),
    MOTIVATE_("EVEN COMIC SANS BELIEVES IN YOU"),
    MOTIVATE_("I AM A SETTINGS TOGGLE AND EVEN I CARE ABOUT YOU"),
    MOTIVATE_("YES, THAT BLUE, PERFECT"),
    MOTIVATE_("YOUR RAM IS PROUD OF YOU"),
    MOTIVATE_("SOMEWHERE, A BEZIER CURVE SMILES"),
    MOTIVATE_("GO ON, RASTERIZE SOMETHING"),
    MOTIVATE_("YOUR GPU IS WARM WITH PRIDE"),
    MOTIVATE_("THE UNDO STACK HAS YOUR BACK, LITERALLY"),
    MOTIVATE_("PIXELS ARE TINY BUT YOUR DREAMS ARE NOT"),
    MOTIVATE_("A WILD MASTERPIECE APPEARS"),
    MOTIVATE_("THIS MESSAGE IS LEGALLY OBLIGATED TO BELIEVE IN YOU"),
    MOTIVATE_("THE CURSOR BLINKS IN ADMIRATION"),
    MOTIVATE_("FILE, NEW, MASTERPIECE"),
    MOTIVATE_("YOUR ANTIALIASING IS IMMACULATE"),
    MOTIVATE_("STAY BETWEEN THE GUIDES, OR DO NOT"),
    MOTIVATE_("THE OPACITY SLIDER TRUSTS YOUR JUDGMENT"),
    MOTIVATE_("SHIP IT, THE CANVAS IS READY"),
    MOTIVATE_("100 PERCENT ZOOM, 100 PERCENT LEGEND"),
    MOTIVATE_("THE EYEDROPPER PICKED YOU"),
    MOTIVATE_("NEW LAYER, NEW ME"),
    MOTIVATE_("YOUR HISTOGRAM IS BEAUTIFUL TONIGHT"),
    MOTIVATE_("THE MARCHING ANTS SALUTE YOU"),
    MOTIVATE_("STAY HYDRATED, YOU MAGNIFICENT ARTIST"),
    MOTIVATE_("THE BACKGROUND LAYER WHISPERS, NICE"),
    MOTIVATE_("DELETE THE DOUBT, KEEP THE DRAWING"),
    MOTIVATE_("PROFESSIONAL TIP, YOU ARE DOING GREAT"),
    MOTIVATE_("ADD A LITTLE GUY IN THE CORNER, TRUST ME"),
    MOTIVATE_("NOW GET BACK TO WORK, CHAMPION"),
    MOTIVATE_("THE LAYERS ARE STACKING IN YOUR FAVOR"),
    MOTIVATE_("EVERY GREAT ARTIST HAS A MESSY UNDO HISTORY"),
    MOTIVATE_("YOUR BRUSH IS BASICALLY A MAGIC WAND"),
    MOTIVATE_("SOMEWHERE A PRINTER IS EXCITED TO MEET THIS"),
    MOTIVATE_("THE CANVAS IS LUCKY TO HAVE YOU"),
    MOTIVATE_("THAT FLAT COLOR IS A MASTERPIECE WAITING TO HAPPEN"),
    MOTIVATE_("NOT TODAY, GRADIENT, WE BELIEVE IN HARD EDGES"),
    MOTIVATE_("YOUR DPI IS THROUGH THE ROOF"),
    MOTIVATE_("SAVE NOW, THANK ME LATER"),
    MOTIVATE_("BREATHE IN, ZOOM OUT"),
    MOTIVATE_("THE COLOR PICKER ADMIRES YOUR RANGE"),
    MOTIVATE_("THE TOOLBAR IS ROOTING FOR YOU"),
    MOTIVATE_("YOUR SELECTION IS PERFECTLY FEATHERED"),
    MOTIVATE_("KEEP CALM AND FLATTEN ON"),
    MOTIVATE_("A TINY GUY, IN THE CORNER, YOU KNOW YOU WANT TO"),
    MOTIVATE_("THE ALPHA CHANNEL HAS YOUR BACK"),
    MOTIVATE_("EVERY PIXEL YOU PLACE IS A DECISION ONLY YOU MADE"),
    MOTIVATE_("YOUR SWATCHES ARE LOOKING SHARP"),
    MOTIVATE_("WARNING, EXCESSIVE TALENT DETECTED"),
    MOTIVATE_("THE GRID IS ALIGNED AND SO ARE YOU"),
    MOTIVATE_("THE SPACEBAR IS HERE WHENEVER YOU NEED TO PAN AWAY"),
    MOTIVATE_("HONK IF YOU LOVE BEZIER HANDLES"),
    MOTIVATE_("THE HUE WHEEL TURNS, AND IT TURNS FOR YOU"),
    MOTIVATE_("REMEMBER TO NAME YOUR LAYERS, LEGEND"),
    MOTIVATE_("YOUR CANVAS HAS NEVER LOOKED MORE CANVAS"),
    MOTIVATE_("DENOISE THE DOUBT, KEEP THE SIGNAL"),
};
constexpr std::size_t kLineCount = std::size(kLines);

}  // namespace

const char* randomMotivationalLine() {
    static thread_local std::mt19937 rng{std::random_device{}()};
    // Avoid repeating any of the last few lines, so a session does not feel small (the user's
    // worry): keep a short ring of recent indices and re-roll a handful of times on a collision.
    static thread_local std::deque<std::size_t> recent;
    std::uniform_int_distribution<std::size_t> pick(0, kLineCount - 1);
    const std::size_t window = std::min<std::size_t>(kLineCount / 2, 24);
    std::size_t idx = pick(rng);
    for (int tries = 0;
         tries < 8 && std::find(recent.begin(), recent.end(), idx) != recent.end(); ++tries)
        idx = pick(rng);
    recent.push_back(idx);
    if (recent.size() > window)
        recent.pop_front();

    const char* line = kLines[idx];
    const char* tr = common::i18n::dtr("motivate", line);
    return (tr != nullptr && *tr != '\0') ? tr : line; // belt + suspenders: never null/empty
}

std::size_t motivationalLineCount() { return kLineCount; }

}  // namespace mosaic::ui
