#pragma once

#include <cstddef>
#include <cstdint>

// GENERATED by tools/gen_world_map.py from Natural Earth 110m land polygons -- DO
// NOT EDIT. See world_map_data.cpp for provenance/licensing. A simplified world
// coastline for the Texture Generator's map place-picker (ui/map_picker.*): closed
// rings of quantized vertices, outer coasts and inner holes listed alike so an
// even-odd fill needs no winding distinction.
namespace mosaic::ui::worldmap {

struct MapPoint {
    std::int16_t lonCenti; // longitude * 100, +E, [-18000, 18000]
    std::int16_t latCenti; // latitude  * 100, +N, [-9000, 9000]
};

// One closed ring: vertices [first, first + count) of mapPoints(); the edge from
// the last vertex back to the first is implied (no repeated closing vertex).
struct MapRing {
    std::uint32_t first;
    std::uint32_t count;
};

[[nodiscard]] const MapPoint* mapPoints() noexcept;
[[nodiscard]] std::size_t mapPointCount() noexcept;
[[nodiscard]] const MapRing* mapRings() noexcept;
[[nodiscard]] std::size_t mapRingCount() noexcept;

}  // namespace mosaic::ui::worldmap
