#pragma once

#include <cstdint>

// GENERATED by tools/gen_moon_elevation.py from NASA's LRO LOLA elevation grid -- DO NOT EDIT.
// See moon_elevation.cpp for provenance/licensing. Height in METRES above the Moon's 1737.4 km
// reference sphere, on the SAME 1024 x 512 equirectangular selenographic grid as the
// albedo map (moon_texture.hpp) -- one (u, v) addresses both. The night-sky renderer
// differentiates it into a terrain-perturbed shading normal, so real crater/maria relief
// roughens the terminator exactly where a photograph shows it.
//
// Layout (row-major, 1024 x 512, identical to moon_texture.hpp):
//   - column 0..W  -> selenographic longitude -180 deg (left) .. +180 deg (right); the prime
//     meridian is at column W/2, longitude increasing EAST-to-the-RIGHT.
//   - row 0..H     -> selenographic latitude +90 deg (north, top) .. -90 deg (south, bottom).
namespace mosaic::core::texture {

inline constexpr int kMoonElevationWidth = 1024;
inline constexpr int kMoonElevationHeight = 512;

// The elevation map: kMoonElevationWidth * kMoonElevationHeight int16 samples, metres.
[[nodiscard]] const std::int16_t* moonElevation() noexcept;

}  // namespace mosaic::core::texture
