#pragma once

#include <cstddef>

// GENERATED by tools/gen_moon_texture.py from NASA's LRO lunar albedo map -- DO NOT EDIT.
// See moon_texture.cpp for provenance/licensing. An 8-bit grayscale equirectangular selenographic
// albedo map of the Moon (the real maria / highlands / ray craters), sphere-mapped onto the lunar
// disc by the night-sky renderer so the actual near-side face appears, phase-lit by the scene sun.
//
// Layout (row-major, 1024 x 512):
//   - column 0..W  -> selenographic longitude -180 deg (left) .. +180 deg (right); the prime
//     meridian (mean sub-Earth point) is at column W/2, longitude increasing EAST-to-the-RIGHT.
//   - row 0..H     -> selenographic latitude +90 deg (north, top) .. -90 deg (south, bottom).
namespace mosaic::core::texture {

inline constexpr int kMoonTextureWidth = 1024;
inline constexpr int kMoonTextureHeight = 512;

// The albedo map: kMoonTextureWidth * kMoonTextureHeight bytes, one grayscale sample per texel.
[[nodiscard]] const unsigned char* moonAlbedo() noexcept;

}  // namespace mosaic::core::texture
