#pragma once

#include <cstddef>

// GENERATED by tools/gen_star_catalog.py from the Yale Bright Star Catalogue -- DO NOT EDIT.
// See star_catalog.cpp for provenance/licensing. The night-sky renderer projects these by their
// true J2000 position (via lunar.hpp's sidereal-time + equatorial->horizontal transforms) so real
// constellations appear; magnitude drives brightness and the colour temperature drives the tint.
namespace mosaic::core::texture {

struct StarEntry {
    float raDeg;    // right ascension, J2000, degrees [0, 360)
    float decDeg;   // declination, J2000, degrees [-90, 90]
    float mag;      // visual magnitude V (smaller = brighter; Sirius = -1.46)
    float kelvin;   // colour temperature for the star's tint
};

// The naked-eye catalogue (V <= 6.5), 8404 stars, in Harvard Revised (HR) order.
[[nodiscard]] const StarEntry* starCatalog() noexcept;
[[nodiscard]] std::size_t starCatalogCount() noexcept;

}  // namespace mosaic::core::texture
