#!/usr/bin/env python3
"""Generate src/core/texture/star_catalog.{hpp,cpp} from the Yale Bright Star Catalogue.

The star positions and magnitudes are astronomical FACTS from the Yale Bright Star Catalogue,
5th ed. (Hoffleit & Warren Jr., 1991) -- public domain. This script consumes the compact
`bsc5-short.json` distilled by Bretton Wade (github.com/brettonw/YaleBrightStarCatalog, MIT),
which also carries a per-star colour temperature K derived from the catalogue's spectral data.
Positions are J2000 (verified: Sirius = 06h45m08.9s / -16d42'58", Vega = 18h36m56.3s / +38d47').

We keep the naked-eye stars (V <= 6.5), each as {raDeg, decDeg, mag, kelvin}. Precession from
J2000 is omitted (< ~0.4 deg through the 2020s -- invisible at a sky texture's scale).

Regenerate:
    gh api repos/brettonw/YaleBrightStarCatalog/contents/bsc5-short.json --jq .content \\
        | base64 -d > bsc5-short.json
    python3 tools/gen_star_catalog.py bsc5-short.json src/core/texture

Credit belongs in docs/credits.md (Yale BSC + the brettonw compact JSON).
"""
import json
import re
import sys

MAG_LIMIT = 6.5  # naked-eye limit -- fainter stars never render at a texture's resolution

RA_RE = re.compile(r"(\d+)h\s*(\d+)m\s*([\d.]+)s")
DEC_RE = re.compile(r"([+-]?)(\d+)\D+(\d+)\D+([\d.]+)")


def parse_ra_deg(s):
    m = RA_RE.search(s)
    if not m:
        return None
    h, mi, se = float(m.group(1)), float(m.group(2)), float(m.group(3))
    return (h + mi / 60.0 + se / 3600.0) * 15.0


def parse_dec_deg(s):
    m = DEC_RE.search(s)
    if not m:
        return None
    sign = -1.0 if m.group(1) == "-" else 1.0
    d, mi, se = float(m.group(2)), float(m.group(3)), float(m.group(4))
    return sign * (d + mi / 60.0 + se / 3600.0)


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "bsc5-short.json"
    outdir = sys.argv[2] if len(sys.argv) > 2 else "src/core/texture"
    data = json.load(open(src, encoding="utf-8"))

    stars = []
    for d in data:
        if not d.get("V") or not d.get("RA") or not d.get("Dec"):
            continue
        try:
            mag = float(d["V"])
        except ValueError:
            continue
        if mag > MAG_LIMIT:
            continue
        ra = parse_ra_deg(d["RA"])
        dec = parse_dec_deg(d["Dec"])
        if ra is None or dec is None:
            continue
        try:
            kelvin = float(d.get("K", "5800"))
        except ValueError:
            kelvin = 5800.0
        kelvin = min(max(kelvin, 1500.0), 40000.0)
        stars.append((ra, dec, mag, kelvin))

    n = len(stars)
    hpp = f"""#pragma once

#include <cstddef>

// GENERATED by tools/gen_star_catalog.py from the Yale Bright Star Catalogue -- DO NOT EDIT.
// See star_catalog.cpp for provenance/licensing. The night-sky renderer projects these by their
// true J2000 position (via lunar.hpp's sidereal-time + equatorial->horizontal transforms) so real
// constellations appear; magnitude drives brightness and the colour temperature drives the tint.
namespace mosaic::core::texture {{

struct StarEntry {{
    float raDeg;    // right ascension, J2000, degrees [0, 360)
    float decDeg;   // declination, J2000, degrees [-90, 90]
    float mag;      // visual magnitude V (smaller = brighter; Sirius = -1.46)
    float kelvin;   // colour temperature for the star's tint
}};

// The naked-eye catalogue (V <= {MAG_LIMIT}), {n} stars, in Harvard Revised (HR) order.
[[nodiscard]] const StarEntry* starCatalog() noexcept;
[[nodiscard]] std::size_t starCatalogCount() noexcept;

}}  // namespace mosaic::core::texture
"""

    lines = []
    row = []
    for (ra, dec, mag, kelvin) in stars:
        row.append(f"{{{ra:.6f}f,{dec:.6f}f,{mag:.2f}f,{kelvin:.1f}f}}")
        if len(row) == 6:
            lines.append("    " + ",".join(row) + ",")
            row = []
    if row:
        lines.append("    " + ",".join(row) + ",")
    body = "\n".join(lines)

    cpp = f"""// GENERATED by tools/gen_star_catalog.py -- DO NOT EDIT.
//
// Data: Yale Bright Star Catalogue, 5th ed. (Hoffleit & Warren Jr., 1991). Star positions and
// magnitudes are astronomical facts (public domain). Distilled via the compact bsc5-short.json of
// Bretton Wade (github.com/brettonw/YaleBrightStarCatalog, MIT), which supplies the per-star colour
// temperature K. Positions are J2000; naked-eye subset (V <= {MAG_LIMIT}); precession omitted. See
// docs/credits.md.

#include "core/texture/star_catalog.hpp"

namespace mosaic::core::texture {{
namespace {{

// {{ raDeg, decDeg, mag, kelvin }}
const StarEntry kStars[] = {{
{body}
}};

}}  // namespace

const StarEntry* starCatalog() noexcept {{ return kStars; }}
std::size_t starCatalogCount() noexcept {{ return sizeof(kStars) / sizeof(kStars[0]); }}

}}  // namespace mosaic::core::texture
"""

    with open(f"{outdir}/star_catalog.hpp", "w", encoding="utf-8") as f:
        f.write(hpp)
    with open(f"{outdir}/star_catalog.cpp", "w", encoding="utf-8") as f:
        f.write(cpp)
    print(f"wrote {n} stars to {outdir}/star_catalog.{{hpp,cpp}}")


if __name__ == "__main__":
    main()
