#!/usr/bin/env python3
"""Generate src/ui/world_map_data.{hpp,cpp} from Natural Earth 110m land polygons.

The world's coastline shape is a geographic FACT. This script consumes Natural Earth's 1:110m
"land" polygons -- PUBLIC DOMAIN ("Free of known copyright restrictions"; naturalearthdata.com,
credit appreciated per their terms) -- via the raw GeoJSON in the nvkelso/natural-earth-vector
GitHub mirror, simplifies each ring with Douglas-Peucker to what survives at flyout scale
(~1 px per degree), quantizes vertices to int16 centidegrees, and emits compact C++ tables --
the same "reference data compiled straight into the tree" approach as star_catalog.{hpp,cpp} /
moon_texture.{hpp,cpp}, but UI-side: the consumer is the Texture Generator's world-map place
picker (src/ui/map_picker.*), which even-odd scanline-fills the rings into a land mask.

Ring convention (relied on by map_picker.cpp):
  - vertices are (lonCenti, latCenti) = degrees * 100 as int16; +E right, +N up;
  - every ring is CLOSED implicitly (last vertex connects back to the first; the GeoJSON
    closing duplicate is dropped);
  - outer coastlines and inner holes (e.g. the Caspian) are listed alike -- even-odd filling
    needs no winding distinction.

Regenerate:
    curl -sSLO https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson
    python3 tools/gen_world_map.py ne_110m_land.geojson src/ui

Credit belongs in docs/credits.md (Natural Earth, public domain).
"""
import json
import sys

TOLERANCE_DEG = 0.25   # Douglas-Peucker tolerance; the flyout draws at ~1 px per degree
MIN_EXTENT_DEG = 0.75  # rings smaller than this across are sub-pixel at flyout scale: dropped


def perp_dist(p, a, b):
    """Perpendicular distance from p to segment a-b (plate-carree degree space)."""
    ax, ay = a
    bx, by = b
    px, py = p
    dx, dy = bx - ax, by - ay
    if dx == 0 and dy == 0:
        return ((px - ax) ** 2 + (py - ay) ** 2) ** 0.5
    t = ((px - ax) * dx + (py - ay) * dy) / (dx * dx + dy * dy)
    t = max(0.0, min(1.0, t))
    cx, cy = ax + t * dx, ay + t * dy
    return ((px - cx) ** 2 + (py - cy) ** 2) ** 0.5


def douglas_peucker(pts, tol):
    """Iterative DP over an open polyline (endpoints kept)."""
    if len(pts) < 3:
        return list(pts)
    keep = [False] * len(pts)
    keep[0] = keep[-1] = True
    stack = [(0, len(pts) - 1)]
    while stack:
        i0, i1 = stack.pop()
        if i1 <= i0 + 1:
            continue
        dmax, imax = -1.0, -1
        for i in range(i0 + 1, i1):
            d = perp_dist(pts[i], pts[i0], pts[i1])
            if d > dmax:
                dmax, imax = d, i
        if dmax > tol:
            keep[imax] = True
            stack.append((i0, imax))
            stack.append((imax, i1))
    return [p for p, k in zip(pts, keep) if k]


def rings_of(geometry):
    t = geometry["type"]
    if t == "Polygon":
        yield from geometry["coordinates"]
    elif t == "MultiPolygon":
        for poly in geometry["coordinates"]:
            yield from poly


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "ne_110m_land.geojson"
    outdir = sys.argv[2] if len(sys.argv) > 2 else "src/ui"
    data = json.load(open(src, encoding="utf-8"))

    total_in = 0
    rings = []
    for feature in data["features"]:
        for ring in rings_of(feature["geometry"]):
            pts = [(float(lon), float(lat)) for lon, lat in ring]
            if len(pts) > 1 and pts[0] == pts[-1]:
                pts = pts[:-1]  # drop the GeoJSON closing duplicate; closure is implied
            total_in += len(pts)
            pts = douglas_peucker(pts, TOLERANCE_DEG)
            # Quantize to centidegrees, dropping vertices the grid collapses together.
            q = []
            for lon, lat in pts:
                v = (round(lon * 100.0), round(lat * 100.0))
                if not q or v != q[-1]:
                    q.append(v)
            if len(q) > 1 and q[0] == q[-1]:
                q = q[:-1]
            if len(q) < 3:
                continue
            lons = [p[0] for p in q]
            lats = [p[1] for p in q]
            if max(max(lons) - min(lons), max(lats) - min(lats)) < MIN_EXTENT_DEG * 100:
                continue  # sub-pixel island at flyout scale
            for lon, lat in q:
                assert -18000 <= lon <= 18000 and -9000 <= lat <= 9000, (lon, lat)
            rings.append(q)

    total_out = sum(len(r) for r in rings)
    print(f"{len(rings)} rings, {total_in} -> {total_out} vertices "
          f"({4 * total_out} point bytes)")

    provenance = (
        "// GENERATED by tools/gen_world_map.py -- DO NOT EDIT.\n"
        "//\n"
        "// Data: Natural Earth 1:110m \"land\" polygons (naturalearthdata.com), PUBLIC DOMAIN\n"
        "// (\"Free of known copyright restrictions\"; credit appreciated per their terms -- see\n"
        "// docs/credits.md), via the raw GeoJSON in the nvkelso/natural-earth-vector mirror.\n"
        f"// Douglas-Peucker tolerance {TOLERANCE_DEG} deg, rings under {MIN_EXTENT_DEG} deg\n"
        f"// across dropped, vertices quantized to int16 centidegrees: {len(rings)} rings,\n"
        f"// {total_out} vertices.\n"
    )

    hpp_path = f"{outdir.rstrip('/')}/world_map_data.hpp"
    cpp_path = f"{outdir.rstrip('/')}/world_map_data.cpp"

    with open(hpp_path, "w", encoding="utf-8") as f:
        f.write(
            "#pragma once\n"
            "\n"
            "#include <cstddef>\n"
            "#include <cstdint>\n"
            "\n"
            "// GENERATED by tools/gen_world_map.py from Natural Earth 110m land polygons -- DO\n"
            "// NOT EDIT. See world_map_data.cpp for provenance/licensing. A simplified world\n"
            "// coastline for the Texture Generator's map place-picker (ui/map_picker.*): closed\n"
            "// rings of quantized vertices, outer coasts and inner holes listed alike so an\n"
            "// even-odd fill needs no winding distinction.\n"
            "namespace mosaic::ui::worldmap {\n"
            "\n"
            "struct MapPoint {\n"
            "    std::int16_t lonCenti; // longitude * 100, +E, [-18000, 18000]\n"
            "    std::int16_t latCenti; // latitude  * 100, +N, [-9000, 9000]\n"
            "};\n"
            "\n"
            "// One closed ring: vertices [first, first + count) of mapPoints(); the edge from\n"
            "// the last vertex back to the first is implied (no repeated closing vertex).\n"
            "struct MapRing {\n"
            "    std::uint32_t first;\n"
            "    std::uint32_t count;\n"
            "};\n"
            "\n"
            "[[nodiscard]] const MapPoint* mapPoints() noexcept;\n"
            "[[nodiscard]] std::size_t mapPointCount() noexcept;\n"
            "[[nodiscard]] const MapRing* mapRings() noexcept;\n"
            "[[nodiscard]] std::size_t mapRingCount() noexcept;\n"
            "\n"
            "}  // namespace mosaic::ui::worldmap\n"
        )

    with open(cpp_path, "w", encoding="utf-8") as f:
        f.write(provenance)
        f.write(
            "\n"
            '#include "ui/world_map_data.hpp"\n'
            "\n"
            "namespace mosaic::ui::worldmap {\n"
            "namespace {\n"
            "\n"
            "// { lonCenti, latCenti }\n"
            "const MapPoint kPoints[] = {\n"
        )
        line = "    "
        for ring in rings:
            for lon, lat in ring:
                cell = f"{{{lon},{lat}}},"
                if len(line) + len(cell) > 100:
                    f.write(line + "\n")
                    line = "    "
                line += cell
        if line.strip():
            f.write(line + "\n")
        f.write(
            "};\n"
            "\n"
            "// { first, count }\n"
            "const MapRing kRings[] = {\n"
        )
        line = "    "
        first = 0
        for ring in rings:
            cell = f"{{{first},{len(ring)}}},"
            if len(line) + len(cell) > 100:
                f.write(line + "\n")
                line = "    "
            line += cell
            first += len(ring)
        if line.strip():
            f.write(line + "\n")
        f.write(
            "};\n"
            "\n"
            "} // namespace\n"
            "\n"
            "const MapPoint* mapPoints() noexcept { return kPoints; }\n"
            "std::size_t mapPointCount() noexcept { return sizeof(kPoints) / sizeof(kPoints[0]); }\n"
            "const MapRing* mapRings() noexcept { return kRings; }\n"
            "std::size_t mapRingCount() noexcept { return sizeof(kRings) / sizeof(kRings[0]); }\n"
            "\n"
            "}  // namespace mosaic::ui::worldmap\n"
        )
    print(f"wrote {hpp_path} + {cpp_path}")


if __name__ == "__main__":
    main()
