#!/usr/bin/env python3
"""Generate src/core/texture/moon_texture.{hpp,cpp} from a NASA LRO lunar albedo map.

The lunar near-side albedo pattern (the maria, the highlands, the bright ray craters) is a
photographic FACT of the Moon's surface, imaged by NASA's Lunar Reconnaissance Orbiter and
published as public-domain data. This script consumes the NASA Scientific Visualization Studio
"CGI Moon Kit" colour map (SVS animation 4720, `lroc_color_poles_2k.tif`, 2048x1024, an
equirectangular selenographic map with the poles filled), converts it to 8-bit grayscale
luminance, downsamples to a compact size, and emits it as a C++ byte array -- the same
"celestial reference data compiled straight into core" approach as star_catalog.{hpp,cpp}.

Grayscale is deliberate: at the scale a moon occupies in a sky texture the surface's faint
colour is invisible, the renderer tints the disc with its own warm moonlight, and grayscale
halves the embedded size. The map is stored in NASA's native display (sRGB) encoding; the
renderer reads value/255 as a relative albedo (maria ~0.35, highlands ~0.75 -- the ~2:1 visual
contrast a real photograph shows).

Equirectangular convention (documented in moon_texture.hpp and relied on by sky_render.cpp):
  - column 0..W maps to selenographic longitude -180 deg (left) .. +180 deg (right); the prime
    meridian / mean sub-Earth point sits at column W/2. Longitude increases EAST-to-the-RIGHT
    (IAU positive-east), verified against Mare Crisium sitting right of centre.
  - row 0..H maps to selenographic latitude +90 deg (north, top) .. -90 deg (south, bottom).

Regenerate:
    curl -sSO https://svs.gsfc.nasa.gov/vis/a000000/a004700/a004720/lroc_color_poles_2k.tif
    python3 tools/gen_moon_texture.py lroc_color_poles_2k.tif src/core/texture

Credit belongs in docs/credits.md (NASA's Scientific Visualization Studio; LROC/ASU/GSFC).
"""
import sys

import numpy as np
from PIL import Image

OUT_W = 1024  # embedded map width  (near hemisphere spans OUT_W/2 = 512 px across its diameter)
OUT_H = 512   # embedded map height


def main():
    if len(sys.argv) != 3:
        sys.exit(f"usage: {sys.argv[0]} <lroc_color_poles_2k.tif> <out_dir>")
    src, out_dir = sys.argv[1], sys.argv[2].rstrip("/")

    im = Image.open(src).convert("RGB")
    a = np.asarray(im).astype(np.float64)
    # Rec. 709 luminance of the (already display-encoded) colour map.
    lum = 0.2126 * a[..., 0] + 0.7152 * a[..., 1] + 0.0722 * a[..., 2]
    gray = Image.fromarray(np.clip(lum, 0, 255).astype(np.uint8), "L")
    gray = gray.resize((OUT_W, OUT_H), Image.LANCZOS)
    data = np.asarray(gray, dtype=np.uint8).reshape(-1)  # row-major, top row first
    assert data.size == OUT_W * OUT_H

    header = f"""\
#pragma once

#include <cstddef>

// GENERATED by tools/gen_moon_texture.py from NASA's LRO lunar albedo map -- DO NOT EDIT.
// See moon_texture.cpp for provenance/licensing. An 8-bit grayscale equirectangular selenographic
// albedo map of the Moon (the real maria / highlands / ray craters), sphere-mapped onto the lunar
// disc by the night-sky renderer so the actual near-side face appears, phase-lit by the scene sun.
//
// Layout (row-major, {OUT_W} x {OUT_H}):
//   - column 0..W  -> selenographic longitude -180 deg (left) .. +180 deg (right); the prime
//     meridian (mean sub-Earth point) is at column W/2, longitude increasing EAST-to-the-RIGHT.
//   - row 0..H     -> selenographic latitude +90 deg (north, top) .. -90 deg (south, bottom).
namespace mosaic::core::texture {{

inline constexpr int kMoonTextureWidth = {OUT_W};
inline constexpr int kMoonTextureHeight = {OUT_H};

// The albedo map: kMoonTextureWidth * kMoonTextureHeight bytes, one grayscale sample per texel.
[[nodiscard]] const unsigned char* moonAlbedo() noexcept;

}}  // namespace mosaic::core::texture
"""
    with open(f"{out_dir}/moon_texture.hpp", "w") as f:
        f.write(header)

    # Emit the bytes as a compact decimal array (like star_catalog.cpp's initializer lists), 40
    # per line so the C++ compiler -- not the interpreted-CMake byte converter, which is too slow
    # for anything past a small SVG -- does the embedding.
    lines = []
    for i in range(0, data.size, 40):
        lines.append(",".join(str(int(v)) for v in data[i : i + 40]))
    body = ",\n    ".join(lines)

    cpp = f"""\
// GENERATED by tools/gen_moon_texture.py -- DO NOT EDIT.
//
// Data: NASA Scientific Visualization Studio "CGI Moon Kit" (SVS 4720), LRO/LROC colour map
// `lroc_color_poles_2k.tif` (an equirectangular selenographic albedo map derived from Lunar
// Reconnaissance Orbiter imagery, ASU/GSFC). NASA material is not copyrighted; credit "NASA's
// Scientific Visualization Studio" is requested and given in docs/credits.md. Converted to 8-bit
// grayscale luminance and downsampled to {OUT_W}x{OUT_H}. The surface pattern is a photographic
// fact of the Moon; this file is a table of that fact, like star_catalog.cpp for the stars.

#include "core/texture/moon_texture.hpp"

namespace mosaic::core::texture {{
namespace {{

const unsigned char kMoonAlbedo[kMoonTextureWidth * kMoonTextureHeight] = {{
    {body}
}};

}}  // namespace

const unsigned char* moonAlbedo() noexcept {{ return kMoonAlbedo; }}

}}  // namespace mosaic::core::texture
"""
    with open(f"{out_dir}/moon_texture.cpp", "w") as f:
        f.write(cpp)

    print(f"wrote {out_dir}/moon_texture.hpp and moon_texture.cpp "
          f"({OUT_W}x{OUT_H}, {data.size} bytes)")


if __name__ == "__main__":
    main()
