#!/usr/bin/env python3
"""Generate src/core/texture/moon_elevation.{hpp,cpp} from the NASA LRO LOLA elevation grid.

The Moon's global topography -- the low maria basins, the crater rims, the highland relief that
roughens a real terminator -- is a measured FACT of the lunar surface, mapped by the Lunar
Orbiter Laser Altimeter (LOLA) aboard NASA's Lunar Reconnaissance Orbiter and published as
public-domain PDS data. This script consumes the LOLA GDR cylindrical grid `LDEM_4.IMG`
(1440x720, 4 pixel/degree, headerless LSB int16 described by the detached LDEM_4.LBL label:
DN * 0.5 = metres of height above the 1737.4 km reference sphere), resamples it onto the SAME
1024x512 equirectangular grid as the albedo map (moon_texture.cpp), and emits it as a C++ int16
array in whole metres -- the renderer differentiates it into the terminator-relief shading
normal (sky_render.cpp), so the table stays raw survey data.

Grid convention (identical to moon_texture.hpp's, so one (u, v) addresses both maps):
  - column 0..W maps to selenographic longitude -180 deg (left) .. +180 deg (right); the prime
    meridian sits at column W/2, longitude increasing EAST-to-the-RIGHT (IAU positive-east).
  - row 0..H maps to selenographic latitude +90 deg (north, top) .. -90 deg (south, bottom).
The alignment of BOTH embedded maps to this convention was verified against the real Moon:
Mare Crisium (+59E, +17N) samples dark (albedo ~85/255) AND ~3.5 km deep -- the true basin
floor -- and the global albedo/elevation correlation (+0.34, bright highlands high) beats the
mirrored candidate (+0.20).

The source grid is pixel-registered: DEM column s is centred at longitude (s + 0.5)/4 deg
east (0..360, so the output's -180..180 wraps through it) and DEM row r at latitude
(359.5 - r)/4 deg. Bilinear resampling (a 1.4x downsample) smooths at the scale the shading
gradient wants anyway.

Regenerate:
    curl -sSO https://imbrium.mit.edu/DATA/LOLA_GDR/CYLINDRICAL/IMG/LDEM_4.IMG
    python3 tools/gen_moon_elevation.py LDEM_4.IMG src/core/texture

Credit belongs in docs/credits.md (NASA LRO / LOLA instrument team, GSFC).
"""
import sys

import numpy as np

OUT_W = 1024  # matches kMoonTextureWidth (one (u, v) addresses albedo and elevation alike)
OUT_H = 512
DEM_W = 1440  # LDEM_4: 4 pixel/degree
DEM_H = 720


def main():
    if len(sys.argv) != 3:
        sys.exit(f"usage: {sys.argv[0]} <LDEM_4.IMG> <out_dir>")
    src, out_dir = sys.argv[1], sys.argv[2].rstrip("/")

    dem = np.fromfile(src, dtype="<i2")
    assert dem.size == DEM_W * DEM_H, f"expected {DEM_W}x{DEM_H} int16, got {dem.size} samples"
    dem = dem.reshape(DEM_H, DEM_W).astype(np.float64) * 0.5  # DN * SCALING_FACTOR -> metres

    # Bilinear resample onto the albedo grid (longitude wraps, latitude clamps at the poles).
    ys, xs = np.meshgrid(np.arange(OUT_H), np.arange(OUT_W), indexing="ij")
    lon = (xs + 0.5) / OUT_W * 360.0 - 180.0  # -180 (left) .. +180 (right), east-positive
    lat = 90.0 - (ys + 0.5) / OUT_H * 180.0
    cf = np.mod(lon, 360.0) * 4.0 - 0.5  # DEM column s is centred at lon (s + 0.5)/4
    rf = 359.5 - lat * 4.0               # DEM row r is centred at lat (359.5 - r)/4
    c0 = np.floor(cf).astype(int)
    r0 = np.floor(rf).astype(int)
    tc = cf - c0
    tr = rf - r0
    c0w = np.mod(c0, DEM_W)
    c1w = np.mod(c0 + 1, DEM_W)
    r0c = np.clip(r0, 0, DEM_H - 1)
    r1c = np.clip(r0 + 1, 0, DEM_H - 1)
    top = dem[r0c, c0w] * (1.0 - tc) + dem[r0c, c1w] * tc
    bot = dem[r1c, c0w] * (1.0 - tc) + dem[r1c, c1w] * tc
    h = top * (1.0 - tr) + bot * tr
    data = np.rint(h).astype(np.int64).reshape(-1)
    assert data.min() >= -32768 and data.max() <= 32767, "metres overflow int16"

    header = f"""\
#pragma once

#include <cstdint>

// GENERATED by tools/gen_moon_elevation.py from NASA's LRO LOLA elevation grid -- DO NOT EDIT.
// See moon_elevation.cpp for provenance/licensing. Height in METRES above the Moon's 1737.4 km
// reference sphere, on the SAME {OUT_W} x {OUT_H} equirectangular selenographic grid as the
// albedo map (moon_texture.hpp) -- one (u, v) addresses both. The night-sky renderer
// differentiates it into a terrain-perturbed shading normal, so real crater/maria relief
// roughens the terminator exactly where a photograph shows it.
//
// Layout (row-major, {OUT_W} x {OUT_H}, identical to moon_texture.hpp):
//   - column 0..W  -> selenographic longitude -180 deg (left) .. +180 deg (right); the prime
//     meridian is at column W/2, longitude increasing EAST-to-the-RIGHT.
//   - row 0..H     -> selenographic latitude +90 deg (north, top) .. -90 deg (south, bottom).
namespace mosaic::core::texture {{

inline constexpr int kMoonElevationWidth = {OUT_W};
inline constexpr int kMoonElevationHeight = {OUT_H};

// The elevation map: kMoonElevationWidth * kMoonElevationHeight int16 samples, metres.
[[nodiscard]] const std::int16_t* moonElevation() noexcept;

}}  // namespace mosaic::core::texture
"""
    with open(f"{out_dir}/moon_elevation.hpp", "w") as f:
        f.write(header)

    # Compact decimal array, 28 per line (the values are wider than albedo bytes) -- the C++
    # compiler does the embedding, as for moon_texture.cpp / star_catalog.cpp.
    lines = []
    for i in range(0, data.size, 28):
        lines.append(",".join(str(int(v)) for v in data[i : i + 28]))
    body = ",\n    ".join(lines)

    cpp = f"""\
// GENERATED by tools/gen_moon_elevation.py -- DO NOT EDIT.
//
// Data: NASA Lunar Reconnaissance Orbiter, Lunar Orbiter Laser Altimeter (LOLA) Gridded Data
// Record `LDEM_4.IMG` (PDS data set LRO-L-LOLA-4-GDR-V1.0, cylindrical 4 pixel/degree grid,
// LOLA science team, D. E. Smith PI, NASA Goddard Space Flight Center). NASA material is not
// copyrighted; credit to the LRO/LOLA team is requested and given in docs/credits.md. Resampled
// to {OUT_W}x{OUT_H} and stored as whole metres of height above the 1737.4 km reference sphere.
// The relief is a measured fact of the lunar surface; this file is a table of that fact, like
// moon_texture.cpp for the albedo and star_catalog.cpp for the stars.

#include "core/texture/moon_elevation.hpp"

namespace mosaic::core::texture {{
namespace {{

const std::int16_t kMoonElevation[kMoonElevationWidth * kMoonElevationHeight] = {{
    {body}
}};

}}  // namespace

const std::int16_t* moonElevation() noexcept {{ return kMoonElevation; }}

}}  // namespace mosaic::core::texture
"""
    with open(f"{out_dir}/moon_elevation.cpp", "w") as f:
        f.write(cpp)

    print(f"wrote {out_dir}/moon_elevation.hpp and moon_elevation.cpp "
          f"({OUT_W}x{OUT_H}, range {data.min()}..{data.max()} m)")


if __name__ == "__main__":
    main()
